//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTR.WPF.DIP.Controls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OTR.WPF.DIP.Controls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual situation.
        /// </summary>
        public static string UcContextTree_ActualSituationText {
            get {
                return ResourceManager.GetString("UcContextTree_ActualSituationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All objects.
        /// </summary>
        public static string UcContextTree_AllObjectsText {
            get {
                return ResourceManager.GetString("UcContextTree_AllObjectsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string UcContextTree_EventsText {
            get {
                return ResourceManager.GetString("UcContextTree_EventsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign OIGs.
        /// </summary>
        public static string UcContextTree_ForeignOIGsText {
            get {
                return ResourceManager.GetString("UcContextTree_ForeignOIGsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign user contexts.
        /// </summary>
        public static string UcContextTree_ForeignUserContextsText {
            get {
                return ResourceManager.GetString("UcContextTree_ForeignUserContextsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holdings.
        /// </summary>
        public static string UcContextTree_HoldingsText {
            get {
                return ResourceManager.GetString("UcContextTree_HoldingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New OIG.
        /// </summary>
        public static string UcContextTree_MenuItemNewOIG {
            get {
                return ResourceManager.GetString("UcContextTree_MenuItemNewOIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New subcontext.
        /// </summary>
        public static string UcContextTree_MenuItemNewSubcontext {
            get {
                return ResourceManager.GetString("UcContextTree_MenuItemNewSubcontext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user context.
        /// </summary>
        public static string UcContextTree_MenuItemNewUserContext {
            get {
                return ResourceManager.GetString("UcContextTree_MenuItemNewUserContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string UcContextTree_MenuItemRefresh {
            get {
                return ResourceManager.GetString("UcContextTree_MenuItemRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove (disassociate from parent content).
        /// </summary>
        public static string UcContextTree_MenuItemRemove {
            get {
                return ResourceManager.GetString("UcContextTree_MenuItemRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string UcContextTree_MenuItemRestore {
            get {
                return ResourceManager.GetString("UcContextTree_MenuItemRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To trash.
        /// </summary>
        public static string UcContextTree_MenuItemToTrash {
            get {
                return ResourceManager.GetString("UcContextTree_MenuItemToTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missions.
        /// </summary>
        public static string UcContextTree_MissionsText {
            get {
                return ResourceManager.GetString("UcContextTree_MissionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Own OIGs.
        /// </summary>
        public static string UcContextTree_OwnOIGsText {
            get {
                return ResourceManager.GetString("UcContextTree_OwnOIGsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Own user contexts.
        /// </summary>
        public static string UcContextTree_OwnUserContextsText {
            get {
                return ResourceManager.GetString("UcContextTree_OwnUserContextsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning and data preparation.
        /// </summary>
        public static string UcContextTree_PlanningAndDataPreparationText {
            get {
                return ResourceManager.GetString("UcContextTree_PlanningAndDataPreparationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans and orders.
        /// </summary>
        public static string UcContextTree_PlansAndOrdersText {
            get {
                return ResourceManager.GetString("UcContextTree_PlansAndOrdersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSP working folder.
        /// </summary>
        public static string UcContextTree_PSPWorkingFolderText {
            get {
                return ResourceManager.GetString("UcContextTree_PSPWorkingFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structures.
        /// </summary>
        public static string UcContextTree_StructuresText {
            get {
                return ResourceManager.GetString("UcContextTree_StructuresText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context tree.
        /// </summary>
        public static string UcContextTree_Title {
            get {
                return ResourceManager.GetString("UcContextTree_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash.
        /// </summary>
        public static string UcContextTree_TrashText {
            get {
                return ResourceManager.GetString("UcContextTree_TrashText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action events ({0}).
        /// </summary>
        public static string UcObjectTree_ActionEvents {
            get {
                return ResourceManager.GetString("UcObjectTree_ActionEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action tasks ({0}).
        /// </summary>
        public static string UcObjectTree_ActionTasks {
            get {
                return ResourceManager.GetString("UcObjectTree_ActionTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facilities ({0}).
        /// </summary>
        public static string UcObjectTree_Facilities {
            get {
                return ResourceManager.GetString("UcObjectTree_Facilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features ({0}).
        /// </summary>
        public static string UcObjectTree_Features {
            get {
                return ResourceManager.GetString("UcObjectTree_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials ({0}).
        /// </summary>
        public static string UcObjectTree_Materials {
            get {
                return ResourceManager.GetString("UcObjectTree_Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not known ({0}).
        /// </summary>
        public static string UcObjectTree_NotKnown {
            get {
                return ResourceManager.GetString("UcObjectTree_NotKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisations ({0}).
        /// </summary>
        public static string UcObjectTree_Organisations {
            get {
                return ResourceManager.GetString("UcObjectTree_Organisations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persons ({0}).
        /// </summary>
        public static string UcObjectTree_Persons {
            get {
                return ResourceManager.GetString("UcObjectTree_Persons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects in context.
        /// </summary>
        public static string UcObjectTree_Title {
            get {
                return ResourceManager.GetString("UcObjectTree_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure tree.
        /// </summary>
        public static string UcStructureTree_Title {
            get {
                return ResourceManager.GetString("UcStructureTree_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Changes.
        /// </summary>
        public static string UcTree_ToolTipClearChanges {
            get {
                return ResourceManager.GetString("UcTree_ToolTipClearChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse all.
        /// </summary>
        public static string UcTree_ToolTipCollapseAll {
            get {
                return ResourceManager.GetString("UcTree_ToolTipCollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse selected item.
        /// </summary>
        public static string UcTree_ToolTipCollapseSelItem {
            get {
                return ResourceManager.GetString("UcTree_ToolTipCollapseSelItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand all.
        /// </summary>
        public static string UcTree_ToolTipExpandAll {
            get {
                return ResourceManager.GetString("UcTree_ToolTipExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand selected item.
        /// </summary>
        public static string UcTree_ToolTipExpandSelItem {
            get {
                return ResourceManager.GetString("UcTree_ToolTipExpandSelItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string UcTree_ToolTipRefresh {
            get {
                return ResourceManager.GetString("UcTree_ToolTipRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string UcTreeListView_ColumnDestcription {
            get {
                return ResourceManager.GetString("UcTreeListView_ColumnDestcription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string UcTreeListView_ColumnName {
            get {
                return ResourceManager.GetString("UcTreeListView_ColumnName", resourceCulture);
            }
        }
    }
}
